export const FETCH_WEATHER_START = 'FETCH_WEATHER_START'
export const FETCH_WEATHER_SUCESSS = 'FETCH_WEATHER_SUCESSS'
export const FETCH_WEATHER_FALI = 'FETCH_WEATHER_FALI'


export const FETCH_FORECAST_START = 'FETCH_FORECAST_START'
export const FETCH_FORECAST_SUCESSS = 'FETCH_FORECAST_SUCESSS'
export const FETCH_FORECAST_FALI = 'FETCH_FORECAST_FALI'